#[workspace]

[package]
name = "wit-bindgen-symmetric-rt"
version = "0.36.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
#wit-bindgen = { path = "../../guest-rust" }

[dependencies.wit-bindgen]
package = "dummy-rt"
path = "../dummy-rt"

[features]
# always off feature
never = []
