[package]
name = "codegen-macro"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.0"
edition.workspace = true
publish = false

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
heck = { workspace = true }
ignore = "0.4"
quote = "1.0.9"
