[package]
name = "wit-bindgen-cli"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version.workspace = true
edition.workspace = true

[workspace]
members = [
  "crates/test-rust-wasm",
  "crates/wasi_snapshot_preview1",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.3.0"

[workspace.dependencies]
anyhow = "1.0.65"
bitflags = "1.3.2"
heck =  { version = "0.4", features = ["unicode"] }
pulldown-cmark = { version = "0.8", default-features = false }
clap = { version = "4.0.9", features = ["derive"] }
env_logger = "0.9.1"
indexmap = "1.9.1"

wasm-encoder = "0.23.0"
wat = "1.0.57"
wit-parser = "0.6.0"
wit-component = "0.6.0"

wit-bindgen-core = { path = 'crates/bindgen-core', version = '0.3.0' }
wit-bindgen-gen-guest-c = { path = 'crates/gen-guest-c', version = '0.3.0' }
wit-bindgen-gen-guest-rust = { path = "crates/gen-guest-rust", version = "0.3.0" }
wit-bindgen-gen-guest-teavm-java = { path = 'crates/gen-guest-teavm-java', version = '0.3.0' }
wit-bindgen-gen-markdown = { path = 'crates/gen-markdown', version = '0.3.0' }
wit-bindgen-gen-rust-lib = { path = 'crates/gen-rust-lib', version = '0.3.0' }
wit-bindgen-guest-rust = { path = 'crates/guest-rust', version = '0.3.0', default-features = false }
wit-bindgen-rust-macro-shared = { path = 'crates/rust-macro-shared', version = '0.3.0' }

[[bin]]
name = "wit-bindgen"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
wit-bindgen-core = { workspace = true }
wit-bindgen-gen-guest-rust = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-gen-guest-c = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-gen-markdown = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-gen-guest-teavm-java = { workspace = true, features = ['clap'], optional = true }
wat = { workspace = true }
wit-component = { workspace = true }

[features]
default = ['c', 'rust', 'markdown', 'teavm-java']
c = ['dep:wit-bindgen-gen-guest-c']
rust = ['dep:wit-bindgen-gen-guest-rust']
markdown = ['dep:wit-bindgen-gen-markdown']
teavm-java = ['dep:wit-bindgen-gen-guest-teavm-java']

[dev-dependencies]
heck = { workspace = true }
wasmtime = { version = "7.0.0", features = ['component-model'] }
test-artifacts = { path = 'crates/test-rust-wasm/artifacts' }
wit-parser = { workspace = true }

[patch.crates-io]
wasmtime = { git = 'https://github.com/bytecodealliance/wasmtime' }
