[package]
name = "wit-bindgen-rust-macro-shared"
version.workspace = true
edition.workspace = true

[lib]
doctest = false
test = false

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
wit-bindgen-core = { workspace = true }
wit-component = { workspace = true }
