[package]
name = "witx-bindgen-wasmtime"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bitflags = "1.2"
thiserror = "1.0"
wasmtime = "0.28"
witx-bindgen-wasmtime-impl = { path = "../wasmtime-impl", version = "0.1" }
tracing-lib = { version = "0.1.26", optional = true, package = 'tracing' }
async-trait = { version = "0.1.50", optional = true }

[dev-dependencies]
wasmtime-wasi = "0.28"
build-test-wasm = { path = '../build-test-wasm' }

[features]
default = ['old-witx-compat'] # TODO: rewrite {host,wasm}.witx with new syntax

# Enables generated code to emit events via the `tracing` crate whenever wasm is
# entered and when native functions are called. Note that tracin is currently
# only done for imported functions.
tracing = ['tracing-lib', 'witx-bindgen-wasmtime-impl/tracing']

# Enables async support for generated code, although when enabled this still
# needs to be configured through the macro invocation.
async = ['async-trait', 'witx-bindgen-wasmtime-impl/async']

# Enables the ability to parse the old s-expression-based `*.witx` format.
old-witx-compat = ['witx-bindgen-wasmtime-impl/old-witx-compat']

[[test]]
name = "run"
harness = false
