[package]
name = "test-helpers"
version.workspace = true
edition.workspace = true
publish = false

[lib]
doctest = false
test = false

[dependencies]
test-helpers-macros = { path = 'macros' }
wit-bindgen-core = { workspace = true }
wit-parser = { workspace = true }

[features]
default = ['guest-rust', 'guest-c', 'guest-teavm-java']
guest-rust = ['test-helpers-macros/guest-rust']
guest-c = ['test-helpers-macros/guest-c']
guest-teavm-java = ['test-helpers-macros/guest-teavm-java']
