[package]
name = "witx-bindgen-rust"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
witx-bindgen-rust-impl = { path = "../rust-wasm-impl" }

[features]
old-witx-compat = ['witx-bindgen-rust-impl/old-witx-compat']
