[package]
name = "witx2"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
id-arena = "2"
anyhow = "1.0"
witx = { version = "0.9.1", optional = true }
wast = { version = "35", default-features = false, optional = true }

[dev-dependencies]
rayon = "1"
serde_json = "1"
serde = { version = "1", features = ['derive'] }

[[test]]
name = "all"
harness = false

[features]
old-witx-compat = ['witx', 'wast']
