[package]
name = "wit-bindgen-gen-guest-teavm-java"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-core = { path = '../bindgen-core', version = '0.2.0' }
heck = { version = "0.4.0", features = [ "unicode" ] }
structopt = { version = "0.3", default-features = false, optional = true }

[dev-dependencies]
test-helpers = { path = '../test-helpers', default-features = false, features = ['guest-teavm-java'] }
