[package]
name = "wit-component"
authors = ["Peter Huene <peter@huene.dev>"]
version.workspace = true
edition.workspace = true

[[bin]]
name = "wit-component"
path = "src/bin/wit-component.rs"
required-features = ["cli"]

[[bin]]
name = "wasm2wit"
path = "src/bin/wasm2wit.rs"
required-features = ["cli"]

[dependencies]
wasmparser = { workspace = true }
wasm-encoder = { workspace = true }
wat = { workspace = true }
wit-parser = { workspace = true }
anyhow = { workspace = true }
indexmap = "1.9.1"
clap = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
log = { version = "0.4.17", optional = true }
bitflags = { workspace = true }

[dev-dependencies]
wasmprinter = { workspace = true }
glob = "0.3.0"
pretty_assertions = "1.3.0"
env_logger = { workspace = true }
test-helpers = { path = '../test-helpers', default-features = false }

[features]
default = ["cli"]
cli = ["clap", "env_logger", "log"]
