[package]
name = "wit-component"
version = "0.2.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2021"

[[bin]]
name = "wit-component"
path = "src/bin/wit-component.rs"
required-features = ["cli"]

[[bin]]
name = "wit2wasm"
path = "src/bin/wit2wasm.rs"
required-features = ["cli"]

[[bin]]
name = "wasm2wit"
path = "src/bin/wasm2wit.rs"
required-features = ["cli"]

[dependencies]
wasmparser = "0.91.0"
wasm-encoder = "0.17.0"
wat = "1.0.49"
wit-parser = { path = "../wit-parser" }
anyhow = "1.0.65"
indexmap = "1.9.1"
clap = { version = "3.2.22", features = ["derive"], optional = true }
env_logger = { version = "0.9.1", optional = true }
log = { version = "0.4.17", optional = true }

[dev-dependencies]
wasmprinter = "0.2.40"
glob = "0.3.0"
pretty_assertions = "1.3.0"

[features]
default = ["cli"]
cli = ["clap", "env_logger", "log"]
