[package]
name = "wit-component"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2021"

[[bin]]
name = "wit2wasm"
path = "src/bin/wit2wasm.rs"
required-features = ["cli"]

[[bin]]
name = "wasm2wit"
path = "src/bin/wasm2wit.rs"
required-features = ["cli"]

[dependencies]
wasmparser = { git = "https://github.com/bytecodealliance/wasm-tools", branch = "component-model" }
wasm-encoder = { git = "https://github.com/bytecodealliance/wasm-tools", branch = "component-model" }
wat = { git = "https://github.com/bytecodealliance/wasm-tools", branch = "component-model" }
wit-parser = { path = "../parser" }
anyhow = "1.0.55"
clap = { version = "3.1.0", features = ["derive"], optional = true }
env_logger = { version = "0.9.0", optional = true }
log = { version = "0.4.14", optional = true }

[features]
default = ["cli"]
cli = ["clap", "env_logger", "log"]
