[package]
name = "wit-bindgen"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.3.0"
edition.workspace = true

[dependencies]
wit-bindgen-guest-rust-macro = { path = "../guest-rust-macro", optional = true }
bitflags = { workspace = true }

[features]
default = ["macros", "realloc"]
macros = ["wit-bindgen-guest-rust-macro"]
realloc = []
