[package]
name = "wit-bindgen-gen-rust-lib"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.3.0"
edition.workspace = true

[lib]
doctest = false
test = false

[dependencies]
wit-bindgen-core = { workspace = true }
heck = { workspace = true }
