[package]
name = "test-modules"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
wasmlink = { path = "../wasmlink" }
wit-parser = { path = "../parser" }

[dev-dependencies]
wasmtime = "0.35.2"
wasmtime-wasi = "0.35.2"
