[package]
name = "test-codegen"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
witx-bindgen-gen-core = { path = '../gen-core' }
witx-bindgen-gen-rust-wasm = { path = '../gen-rust-wasm' }
witx2 = { path = '../witx2' }
