[package]
name = "wit-bindgen-core"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.3.0"
edition.workspace = true

[lib]
doctest = false

[dependencies]
wit-parser = { workspace = true }
anyhow = { workspace = true }
wit-component = { workspace = true }
